# Generated by Django 5.0.6 on 2024-05-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='chiefs/')),
                ('name', models.CharField(max_length=255)),
                ('proffession', models.CharField(max_length=255)),
                ('experience', models.TextField()),
            ],
        ),
    ]
