# Generated by Django 5.0.6 on 2024-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chefs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs',
            name='section',
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sectionName',
        ),
        migrations.AlterField(
            model_name='chefs',
            name='image',
            field=models.ImageField(upload_to='image/chiefs/'),
        ),
    ]
